y = cmdscale(dist_traits(select('Carnivora'),{'a_m'; 'a_p'; 'a_b'; 'Ww_i'; 'Ww_p'; 'Ww_b'; 'R_i'; 's_s'; 's_Hbp'; 'p_M'}),3);
  legend_Carnivora = {...
    % Feliformia, red edge
    {'o', 8, 3, [1 0 0], [0 0 0]}, 'Feloidea'; ...
    {'o', 8, 3, [1 0 0], [1 0 0]}, 'Viverroidea'; ...
    {'o', 8, 3, [1 0 0], [0 0 1]}, 'Eupleridae'; ...
    % Caniformia, blue edge
    {'o', 8, 3, [0 0 1], [0 0 0]}, 'Canidae'; ....
    {'o', 8, 3, [0 0 1], [1 0 0]}, 'Ursidae'; ....
    {'o', 8, 3, [0 0 1], [1 0 1]}, 'Musteloidea'; ....
    {'o', 8, 3, [0 0 1], [0 0 1]}, 'Pinnipedia'; ....
  };

% make sure that the number of rows of data matches the number of entries
data=NaN(length(select),3); data(select_01('Carnivora'),:) = y;
% plot
shstat(data, legend_Carnivora, 'MDS');