%% get_statfields
% returns cell array of strings with names of statistics and a stucture
% with color fields which are needed for the web for a given DEB model

%%
function [webStatFields, webColStat]= get_statfields(model)
% created 2016/09/21 by Starrlight Augustine; modified 2018/08/22 Bas Kooijman
 
  %% Syntax 
  % [webStatFields, webColStat] = <../get_statfields.m *get_statfields*> (model)

  %% Description
  % Provides the list of fields in statistics in the order that they should
  % be printed to the wb
  %
  % Input
  %
  % * model: string with name of model: 'std', 'stf', 'stx', 'ssj', 'sbp', 'abj', 'asj', 'abp', 'hep', 'hex'. 
  %
  % Output
  %
  % * webStatFields: cell string with field names
  % * webColStat: structure with associated colors for each field name
  
  %% Remarks
  % Only applies to generating webpages - change here if we could like to
  % see other things on the web and/ or wish to change the order they
  % appear in on the web

  %% Example of use
  % [webStatFields, webColStat] = get_parfields(metaPar.model)
  
  webColStat.z      = '#FFC6A5'; webColStat.c_T       = '#FFC6A5';
  webColStat.s_M    = '#F7BDDE'; webColStat.s_Hbp     = '#F7BDDE'; webColStat.s_s   = '#F7BDDE';
    
  webColStat.E_0    = '#FFFFFF'; webColStat.Wd_0      = '#FFFFFF';  
  webColStat.a_b    = '#C6E7DE'; webColStat.t_g       = '#C6E7DE';
  webColStat.a_p    = '#C6E7DE'; webColStat.a_99      = '#C6E7DE';
  webColStat.a_j    = '#C6E7DE'; webColStat.a_m       = '#C6E7DE';
  
  webColStat.Ww_b   = '#CEEFBD'; webColStat.Ww_p      = '#CEEFBD'; 
  webColStat.Ww_j   = '#CEEFBD'; webColStat.Ww_i      = '#CEEFBD';
  webColStat.W_dWm  = '#FFFFFF'; webColStat.dWm       = '#FFFFFF';
  
  webColStat.R_i    = '#FFFFC6'; webColStat.N_i       = '#FFFFC6'; 
 
  webColStat.del_Wb = '#FFFF9C'; webColStat.del_Wp   = '#FFFF9C'; webColStat.del_V = '#FFFF9C'; webColStat.r_B = '#FFFF9C'; 
  webColStat.E_m    = '#FFC6A5'; webColStat.t_starve = '#FFC6A5'; webColStat.t_E   = '#FFC6A5'; webColStat.xi_WE = '#FFC6A5'; 
  webColStat.J_Cb   = '#E0E0E0'; webColStat.J_Cp     = '#E0E0E0'; webColStat.J_Ci  = '#E0E0E0';
  webColStat.J_Hb   = '#C6EFF7'; webColStat.J_Hp     = '#C6EFF7'; webColStat.J_Hi  = '#C6EFF7';
  webColStat.J_Ob   = '#CEEFBD'; webColStat.J_Op     = '#CEEFBD'; webColStat.J_Oi  = '#CEEFBD';
  webColStat.J_Nb   = '#FFFFFF'; webColStat.J_Np     = '#FFFFFF'; webColStat.J_Ni  = '#FFFFFF';
  webColStat.p_Ti   = '#FFC6A5';

  
  switch model
      
  case {'std', 'abp', 'sbp'}      
    webStatFields =  {...
    'z'; 'c_T'; ...
    's_Hbp'; 's_s'; ...
    'E_0';'Wd_0'; ...
    'a_b'; 'a_p'; 'a_99'; ...
    'Ww_b'; 'Ww_p'; 'Ww_i'; ...
    'W_dWm'; 'dWm'; ...
    'R_i'; 'N_i'; ...
    'del_Wb'; 'del_Wp'; 'del_V'; 'r_B'; ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'J_Cb'; 'J_Cp'; 'J_Ci'; 'J_Hb'; 'J_Hp'; 'J_Hi'; 'J_Ob'; 'J_Op'; 'J_Oi'; 'J_Nb'; 'J_Np'; 'J_Ni'; 'p_Ti'};
    
  case {'stx', 'stf'}     
    webStatFields =  {...
    'z';  'c_T'; ...
    's_Hbp'; 's_s'; ...
    'a_b'; 't_g'; 'a_p'; 'a_99'; ...
    'Ww_b'; 'Ww_p'; 'Ww_i'; ...
    'W_dWm'; 'dWm'; ...
    'R_i'; 'N_i'; ...
    'del_Wb'; 'del_Wp'; 'del_V'; 'r_B'; ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'J_Cb'; 'J_Cp'; 'J_Ci'; 'J_Hb'; 'J_Hp'; 'J_Hi'; 'J_Ob'; 'J_Op'; 'J_Oi'; 'J_Nb'; 'J_Np'; 'J_Ni'; 'p_Ti'};

  case 'ssj'
     webStatFields =  {...
    'z'; 'c_T'; ...
    's_Hbp'; 's_s'; ...
    'E_0';'Wd_0'; ...
    'a_b'; 'a_p'; 'a_99'; ...
    'Ww_b'; 'Ww_p'; 'Ww_i'; ...
    'W_dWm'; 'dWm'; ...
    'R_i'; 'N_i'; ...
    'del_Wb'; 'del_Wp'; 'del_V'; 'r_B'; ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'J_Cb'; 'J_Cp'; 'J_Ci'; 'J_Hb'; 'J_Hp'; 'J_Hi'; 'J_Ob'; 'J_Op'; 'J_Oi'; 'J_Nb'; 'J_Np'; 'J_Ni'; 'p_Ti'};

  case 'abj'
    webStatFields =  {...
    'z'; 'c_T'; ...
    's_M'; 's_Hbp'; 's_s'; ...
    'E_0'; 'Wd_0'; ...
    'a_b'; 'a_p'; 'a_99'; ...
    'Ww_b'; 'Ww_p'; 'Ww_i'; ...
    'W_dWm'; 'dWm'; ...
    'N_i'; 'R_i';  ...
    'del_Wb'; 'del_Wp'; 'del_V'; 'r_B'; ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'J_Cb'; 'J_Cp'; 'J_Ci'; 'J_Hb'; 'J_Hp'; 'J_Hi'; 'J_Ob'; 'J_Op'; 'J_Oi'; 'J_Nb'; 'J_Np'; 'J_Ni'; 'p_Ti'};
    
  case 'asj'
     webStatFields =  {...
    'z'; 'c_T'; ...
    's_M'; 's_Hbp'; 's_s'; ...
    'E_0';'Wd_0'; ...
    'a_b'; 'a_p'; 'a_99'; ...
    'Ww_b'; 'Ww_p'; 'Ww_i'; ...
    'W_dWm'; 'dWm'; ...
    'N_i'; 'R_i';  ...
    'del_Wb'; 'del_Wp'; 'del_V'; 'r_B'; ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'J_Cb'; 'J_Cp'; 'J_Ci'; 'J_Hb'; 'J_Hp'; 'J_Hi'; 'J_Ob'; 'J_Op'; 'J_Oi'; 'J_Nb'; 'J_Np'; 'J_Ni'; 'p_Ti'};

  case 'hep'
    webStatFields =  {...
    'z'; 'c_T'; ...
    's_M'; 's_Hbp'; 's_s'; ...
    'E_0';'Wd_0'; ...
    'a_b'; 'a_p';  ...
    'Ww_b'; 'Ww_p'; 'Ww_i'; ...
    'W_dWm'; 'dWm'; ...
    'N_i';  ...
    'del_Wb'; 'del_Wp'; 'del_V';  ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'J_Cb'; 'J_Cp'; 'J_Ci'; 'J_Hb'; 'J_Hp'; 'J_Hi'; 'J_Ob'; 'J_Op'; 'J_Oi'; 'J_Nb'; 'J_Np'; 'J_Ni'; 'p_Ti'};

  case 'hex'
     webStatFields =  {...
    'z'; 'c_T'; ...
    's_M';  's_s'; ...
    'E_0';'Wd_0'; ...
    'a_b'; 'a_p';  ...
    'Ww_b'; 'Ww_i'; ...
    'W_dWm'; 'dWm'; ...
    'N_i';   ...
    'del_Wb'; 'del_V';  ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'J_Cb'; 'J_Ci'; 'J_Hb'; 'J_Hi'; 'J_Ob'; 'J_Oi'; 'J_Nb'; 'J_Ni'; 'p_Ti'};  

  otherwise
    webStatFields  = {};     
          
  end
  
  
end
  
  